# Generated by Django 4.0.6 on 2022-07-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Магазин')),
                ('photo', models.ImageField(upload_to='photos_shops/%Y/%m/%d', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URl')),
                ('content', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes-Benz'), ('Porshe', 'Porshe'), ('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Lamborghini', 'Lamborghini'), ('Ferrari', 'Ferrari'), ('Kia', 'Kia'), ('Skoda', 'Skoda'), ('Volkswagen', 'Volkswagen')], max_length=25, verbose_name='Фирма')),
                ('mark', models.CharField(max_length=40, verbose_name='Марка')),
                ('condition', models.CharField(choices=[('by', 'Б/У'), ('new', 'Нове')], max_length=40, verbose_name='Стан')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URl')),
                ('content', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('distance', models.PositiveIntegerField(verbose_name='Пробег')),
                ('power', models.PositiveIntegerField(verbose_name='Лошадок')),
                ('transmission', models.CharField(choices=[('aftomat', 'Автомат'), ('mexanika', 'Механiка')], max_length=40, verbose_name='Коробка')),
                ('fuel', models.CharField(choices=[('petrol', 'Бензин'), ('dizel', 'Дизель'), ('gas', 'Газ'), ('electro', 'Електро')], max_length=40, verbose_name='Паливо')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('shops', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.shops')),
            ],
            options={
                'verbose_name': 'Автомобiль',
                'verbose_name_plural': 'Автомобiлi',
                'ordering': ['id'],
            },
        ),
    ]
