# Generated by Django 4.0.6 on 2022-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='condition',
            field=models.CharField(choices=[('Б/У', 'Б/У'), ('Нове', 'Нове')], max_length=40, verbose_name='Стан'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Газ', 'Газ'), ('Електро', 'Електро')], max_length=40, verbose_name='Паливо'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='transmission',
            field=models.CharField(choices=[('Автомат', 'Автомат'), ('Механiка', 'Механiка')], max_length=40, verbose_name='Коробка'),
        ),
    ]
